import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

public class Login_Page extends javax.swing.JFrame {
String url = "jdbc:mysql://localhost:3306/";  
String database = "passbox_db";   
String driver = "com.mysql.jdbc.Driver";
String username = "root";  
String password = ""; 
Connection connection = null;
Statement command = null;
ResultSet incomingdata = null; 
PreparedStatement pst = null;
    private Object e;
    /**
     * Creates new form Login_Panel
     */
    public Login_Page() {
        initComponents();
        setIcon();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        try {
        Class.forName(driver);
        
        connection = DriverManager.getConnection(url + database, username, password);
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"There was an error with the connection");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jPanel_Login_Page = new javax.swing.JPanel();
        jLabel_Login_Page_username = new javax.swing.JLabel();
        jLabel_Login_Panel_password = new javax.swing.JLabel();
        jButton_Login_Page_Login_Button = new javax.swing.JButton();
        jButton_Login_Page_Create_New_Account = new javax.swing.JButton();
        jButton_Login_Page_Exit_Button = new javax.swing.JButton();
        jButton_Login_Page_Forgot_Account_Button = new javax.swing.JButton();
        username_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        jButton_Login_Page_Contact_Me = new javax.swing.JButton();
        jButton_Login_Panel_Button_Logo = new javax.swing.JButton();
        jLabel_Login_Panel_PassBox_Name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PassBox | Login Panel");
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setName("PassBox"); 
        setResizable(false);

        jLabel_Login_Page_username.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jLabel_Login_Page_username.setText("Username : ");

        jLabel_Login_Panel_password.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jLabel_Login_Panel_password.setText("Password : ");

        jButton_Login_Page_Login_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20));
        jButton_Login_Page_Login_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/login_button.png"))); 
        jButton_Login_Page_Login_Button.setText("Login");
        jButton_Login_Page_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Login_ButtonActionPerformed(evt);
            }
        });

        jButton_Login_Page_Create_New_Account.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jButton_Login_Page_Create_New_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/register_ico.png"))); 
        jButton_Login_Page_Create_New_Account.setText("Create a New Account");
        jButton_Login_Page_Create_New_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Create_New_AccountActionPerformed(evt);
            }
        });

        jButton_Login_Page_Exit_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jButton_Login_Page_Exit_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/exit_ico.png"))); 
        jButton_Login_Page_Exit_Button.setText("Exit");
        jButton_Login_Page_Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Exit_ButtonActionPerformed(evt);
            }
        });

        jButton_Login_Page_Forgot_Account_Button.setFont(new java.awt.Font("Yu Gothic UI", 1, 20));
        jButton_Login_Page_Forgot_Account_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/forgot_password.png")));
        jButton_Login_Page_Forgot_Account_Button.setText("Forgot account ?");
        jButton_Login_Page_Forgot_Account_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Forgot_Account_ButtonActionPerformed(evt);
            }
        });

        username_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); 

        password_txt.setFont(new java.awt.Font("Tahoma", 1, 11)); 

        jButton_Login_Page_Contact_Me.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jButton_Login_Page_Contact_Me.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/contact_us.png"))); 
        jButton_Login_Page_Contact_Me.setText("Contact Me");
        jButton_Login_Page_Contact_Me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login_Page_Contact_MeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Login_PageLayout = new javax.swing.GroupLayout(jPanel_Login_Page);
        jPanel_Login_Page.setLayout(jPanel_Login_PageLayout);
        jPanel_Login_PageLayout.setHorizontalGroup(
            jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_Login_Page_Login_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_Login_PageLayout.createSequentialGroup()
                        .addGroup(jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Login_Page_username)
                            .addComponent(jLabel_Login_Panel_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_txt)
                            .addComponent(password_txt)))
                    .addComponent(jButton_Login_Page_Create_New_Account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Login_Page_Exit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Login_Page_Forgot_Account_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Login_Page_Contact_Me, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Login_PageLayout.setVerticalGroup(
            jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Login_PageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login_Page_username)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Login_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login_Panel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Login_Page_Login_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Login_Page_Forgot_Account_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Login_Page_Create_New_Account)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Login_Page_Contact_Me)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Login_Page_Exit_Button)
                .addGap(56, 56, 56))
        );

        jButton_Login_Panel_Button_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/PassBox.png"))); 
        jButton_Login_Panel_Button_Logo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/PassBox.png"))); 
        jButton_Login_Panel_Button_Logo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/PassBox.png"))); 
        jButton_Login_Panel_Button_Logo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/PassBox.png"))); 

        jLabel_Login_Panel_PassBox_Name.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jLabel_Login_Panel_PassBox_Name.setText("PassBox");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Login_Panel_Button_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel_Login_Panel_PassBox_Name)))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Login_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Login_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Login_Panel_Button_Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Login_Panel_PassBox_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    private void jButton_Login_Page_Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jButton_Login_Page_Forgot_Account_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         this.setVisible(false);
         Forgot_Account_Page frame = new Forgot_Account_Page();
         frame.setVisible(true);         
    }

    private void jButton_Login_Page_Contact_MeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         Contact_Me_Page frame = new Contact_Me_Page();
         frame.setVisible(true); 
    }

    private void jButton_Login_Page_Create_New_AccountActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         this.setVisible(false);
         Create_a_New_Account_Page frame = new Create_a_New_Account_Page();
         frame.setVisible(true); 
        
    }

    private void jButton_Login_Page_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String query = "SELECT * FROM passbox_db.users_tb where username=? and password=?;";
        try {
            pst = connection.prepareStatement(query);
            pst.setString(1, username_txt.getText());
            pst.setString(2, password_txt.getText());
            incomingdata = pst.executeQuery();
            if(incomingdata.next()){
                JOptionPane.showMessageDialog(null,"Login Successful!");
                this.setVisible(false);
                 int id = (Integer) incomingdata.getObject(1);
                User_Control_Panel_Page frame = new User_Control_Panel_Page(id);
                frame.setVisible(true);
            }
            else{
            JOptionPane.showMessageDialog(null,"Login Failed");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "There was an error with the query");
        }
        
    }
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode()==KeyEvent.VK_ENTER){
            String query = "SELECT * FROM passbox_db.users_tb where username=? and password=?;";
        try {
            pst = connection.prepareStatement(query);
            pst.setString(1, username_txt.getText());
            pst.setString(2, password_txt.getText());
            incomingdata = pst.executeQuery();
            if(incomingdata.next()){
                JOptionPane.showMessageDialog(null,"Login Successful!");
                this.setVisible(false);
                User_Control_Panel_Page frame = new User_Control_Panel_Page();
                frame.setVisible(true);
            }
            else{
            JOptionPane.showMessageDialog(null,"Login Failed!");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, "There was an error with the query");
        }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);  
            }
        });
    }
    // Variable declarations
    private javax.swing.JButton jButton_Login_Page_Contact_Me;
    private javax.swing.JButton jButton_Login_Page_Create_New_Account;
    private javax.swing.JButton jButton_Login_Page_Exit_Button;
    private javax.swing.JButton jButton_Login_Page_Forgot_Account_Button;
    private javax.swing.JButton jButton_Login_Page_Login_Button;
    private javax.swing.JButton jButton_Login_Panel_Button_Logo;
    private javax.swing.JLabel jLabel_Login_Page_username;
    private javax.swing.JLabel jLabel_Login_Panel_PassBox_Name;
    private javax.swing.JLabel jLabel_Login_Panel_password;
    private javax.swing.JPanel jPanel_Login_Page;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextField username_txt;
    

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("passbox_ico.png")));
    }
}