import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import java.awt.*;

public class User_Control_Panel_Page extends javax.swing.JFrame {
String url = "jdbc:mysql://localhost:3306/";  
String database = "passbox_db";  
String driver = "com.mysql.jdbc.Driver";
String username = "root";  
String password = ""; 
Connection connection = null;
Statement command =  null;
ResultSet incomingdata = null; 
PreparedStatement pst = null;
    /**
     * Creates new form User_Control_Panel_Page
     */
    public void connection(){
        try {
        Class.forName(driver);
        connection = DriverManager.getConnection(url + database, username , password);
        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("Error 1: Driver and bus!" + ex);
        }
    }
    int id = -1;
     public User_Control_Panel_Page() {
        initComponents();
     }
    public User_Control_Panel_Page(int gid) {
        initComponents();
        setIcon();
        Date today = new Date();
        checkintime_label.setText(today.toString());
        id = gid;
        
    }
    User_Control_Panel_Page(int gidenid, String gidenad) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton_AboutUs = new javax.swing.JButton();
        jButton_ContactMe = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jLabel_User_Control_Panel_Page_usercontrolpanel = new javax.swing.JLabel();
        jButton_UserEdit = new javax.swing.JButton();
        jButton_Database = new javax.swing.JButton();
        jButton_AddPassword = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkintime_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        software_update_button = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PassBox | User Control Page");
        setResizable(false);

        jButton_AboutUs.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_AboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/about_me_ico.png"))); 
        jButton_AboutUs.setText("About Us");
        jButton_AboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AboutUsActionPerformed(evt);
            }
        });

        jButton_ContactMe.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_ContactMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/contact_me_ico.png"))); 
        jButton_ContactMe.setText("Contact Me");
        jButton_ContactMe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ContactMe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_ContactMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ContactMeActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/exit_ico.png"))); 
        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jLabel_User_Control_Panel_Page_usercontrolpanel.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); 
        jLabel_User_Control_Panel_Page_usercontrolpanel.setText("User Control Panel");

        jButton_UserEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_UserEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/user_edit_ico.png"))); 
        jButton_UserEdit.setText("User Edit");
        jButton_UserEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_UserEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_UserEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UserEditActionPerformed(evt);
            }
        });

        jButton_Database.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_Database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/database_ico.png")));
        jButton_Database.setText("Database");
        jButton_Database.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Database.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DatabaseActionPerformed(evt);
            }
        });

        jButton_AddPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton_AddPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/password_management_ico.png")));
        jButton_AddPassword.setText("Manage passwords");
        jButton_AddPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AddPassword.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AddPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddPasswordActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/default_user_ico.png"))); 

        jLabel1.setText(".........");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); 
        jLabel2.setText("System Entry Time : ");

        checkintime_label.setText("            ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/log_file.png"))); 
        jButton1.setText("Log Control");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        software_update_button.setFont(new java.awt.Font("Tahoma", 1, 11)); 
        software_update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/software-update.png"))); 
        software_update_button.setText("Software Update");
        software_update_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        software_update_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        software_update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                software_update_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_User_Control_Panel_Page_usercontrolpanel)
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkintime_label, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(software_update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_UserEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton_AboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ContactMe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton_AddPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Database, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_User_Control_Panel_Page_usercontrolpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(checkintime_label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_UserEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_AddPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Database, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_AboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_ContactMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(software_update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        pack();
    }

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jButton_UserEditActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         User_Edit_Page frame = new User_Edit_Page(id);
         frame.setVisible(true);  
    }

    private void jButton_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         About_Us_Page frame = new About_Us_Page();
         frame.setVisible(true); 
    }

    private void jButton_AddPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
         Management_Password_Page frame = new Management_Password_Page();
         frame.setVisible(true); 
    }

    private void jButton_DatabaseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Database_View frame = new Database_View();
        frame.setVisible(true);
    }

    private void jButton_ContactMeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Contact_Me_Page frame = new Contact_Me_Page();
        frame.setVisible(true);
    }

    private void software_update_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Software_Update_Page frame_softwareupdatepage = new Software_Update_Page();
        frame_softwareupdatepage.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Log_Control_Page frame_logcontrolpage = new Log_Control_Page();
        frame_logcontrolpage.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Control_Panel_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Control_Panel_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Control_Panel_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Control_Panel_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Control_Panel_Page().setVisible(true);
            }
        });
    }

    // Variables declaration 
    private javax.swing.JLabel checkintime_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_AboutUs;
    private javax.swing.JButton jButton_AddPassword;
    private javax.swing.JButton jButton_ContactMe;
    private javax.swing.JButton jButton_Database;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_UserEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_User_Control_Panel_Page_usercontrolpanel;
    private javax.swing.JButton software_update_button;
    

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("passbox_ico.png")));
    }
}
